[build]
command = "npm run build"
publish = "build"

[build.environment]
NODE_VERSION = "20"

[[headers]]
	for = "/_app/immutable/*"
	[headers.values]
		Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
	for = "/_app/*"
	[headers.values]
		Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
	for = "/icon.svg"
	[headers.values]
		Cache-Control = "public, max-age=604800, s-maxage=604800"